# --- !Ups

insert into `books` values
    (   "Gen", 11,     "Ex",    "Apoc"),
    (    "Ex", 11,    "Lev",     "Gen"),
    (   "Lev", 11,    "Num",      "Ex"),
    (   "Num", 11,   "Deut",     "Lev"),
    (  "Deut", 11,    "Jos",     "Num"),

    (   "Jos", 11,    "Jdcs",   "Deut"),
    (  "Jdcs", 11,    "Ruth",    "Jos"),
    (  "Ruth", 11,    "1Reg",   "Jdcs"),
    (  "1Reg", 11,    "2Reg",   "Ruth"),
    (  "2Reg", 11,    "3Reg",   "1Reg"),
    (  "3Reg", 11,    "4Reg",   "2Reg"),
    (  "4Reg", 11,    "1Par",   "3Reg"),
    (  "1Par", 11,    "2Par",   "4Reg"),
    (  "2Par", 11,    "1Esd",   "1Par"),
    (  "1Esd", 11,    "2Esd",   "2Par"),
    (  "2Esd", 11,    "3Esd",   "1Esd"),
    (  "3Esd", 11,    "4Esd",   "2Esd"),
    (  "4Esd", 11,     "Tob",   "3Esd"),
    (   "Tob", 11,    "Jdth",   "4Esd"),
    (  "Jdth", 11,    "Esth",    "Tob"),
    (  "Esth", 11,   "1Mach",   "Jdth"),
    ( "1Mach", 11,   "2Mach",   "Esth"),
    ( "2Mach", 11,   "3Mach",  "1Mach"),
    ( "3Mach", 11,   "4Mach",  "2Mach"),
    ( "4Mach", 11,     "Job",  "3Mach"),

    (   "Job", 11,      "Ps",  "4Mach"),
    (    "Ps", 11,    "Prov",    "Job"),
    (  "Prov", 11,     "Ecc",     "Ps"),
    (   "Ecc", 11,      "CC",   "Prov"),
    (    "CC", 11,     "Sap",    "Ecc"),
    (   "Sap", 11,     "Sir",     "CC"),
    (   "Sir", 11,     "Isa",    "Sap"),

    (   "Isa", 11,     "Jer",    "Sir"),
    (   "Jer", 11,    "Ezch",    "Isa"),
    (  "Ezch", 11,     "Dan",    "Jer"),
    (   "Dan", 11,     "Lam",   "Ezch"),
    (   "Lam", 11,    "EJer",    "Dan"),
    (  "EJer", 11,     "Bar",    "Lam"),
    (   "Bar", 11,    "Osee",   "EJer"),
    (  "Osee", 11,    "Joel",    "Bar"),
    (  "Joel", 11,      "Am",   "Osee"),
    (    "Am", 11,     "Abd",   "Joel"),
    (   "Abd", 11,     "Jon",     "Am"),
    (   "Jon", 11,     "Mic",    "Abd"),
    (   "Mic", 11,     "Nah",    "Jon"),
    (   "Nah", 11,     "Hab",    "Mic"),
    (   "Hab", 11,    "Soph",    "Nah"),
    (  "Soph", 11,     "Agg",    "Hab"),
    (   "Agg", 11,    "Zach",   "Soph"),
    (  "Zach", 11,     "Mal",    "Agg"),
    (   "Mal", 11,      "Mt",   "Zach"),

    (    "Mt", 28,     "Mc",    "Mal"),
    (    "Mc", 16,     "Lc",     "Mt"),
    (    "Lc", 24,     "In",     "Mc"),
    (    "In", 21,    "Act",     "Lc"),

    (   "Act", 11,    "Jac",     "In"),

    (   "Jac", 11,   "1Pet",    "Act"),
    (  "1Pet", 11,   "2Pet",    "Jac"),
    (  "2Pet", 11,    "1In",   "1Pet"),
    (   "1In", 11,    "2In",   "2Pet"),
    (   "2In", 11,    "3In",    "1In"),
    (   "3In", 11,     "Jd",    "2In"),
    (    "Jd", 11,    "Rom",    "3In"),

    (   "Rom", 11,   "1Cor",     "Jd"),
    (  "1Cor", 11,   "2Cor",    "Rom"),
    (  "2Cor", 11,    "Gal",   "1Cor"),
    (   "Gal", 11,    "Eph",   "2Cor"),
    (   "Eph", 11,    "Php",    "Gal"),
    (   "Php", 11,    "Col",    "Eph"),
    (   "Col", 11, "1Thess",    "Php"),
    ("1Thess", 11, "2Thess",    "Col"),
    ("2Thess", 11,   "1Tim", "1Thess"),
    (  "1Tim", 11,   "2Tim", "2Thess"),
    (  "2Tim", 11,    "Tit",   "1Tim"),
    (   "Tit", 11,    "Phm",   "2Tim"),
    (   "Phm", 11,   "Hebr",    "Tit"),
    (  "Hebr", 11,   "Apoc",    "Phm"),

    (  "Apoc", 11,    "Gen",   "Hebr");

# --- !Downs

delete from `books`;

